---
all:
  children:
    linux:
      hosts:
        vm-linuxweb001.eastus.cloudapp.azure.com:
        ec2-54-88-16-230.compute-1.amazonaws.com:
    windows:
      hosts:
        vm-winweb001.eastus.cloudapp.azure.com:
        ec2-54-173-157-198.compute-1.amazonaws.com:
